// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhpAkcM8tqMw5jNbzNIwYZYJh0yI7akZ0',
    appId: '1:241289146857:web:9f363fd130f8510c2f9b78',
    messagingSenderId: '241289146857',
    projectId: 'construfast-ae515',
    authDomain: 'construfast-ae515.firebaseapp.com',
    storageBucket: 'construfast-ae515.firebasestorage.app',
    measurementId: 'G-5QP0VRJS9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABorSWwy9FVzxWXURPRFhMwm1I_XpjgcY',
    appId: '1:241289146857:android:19bf65174070f4352f9b78',
    messagingSenderId: '241289146857',
    projectId: 'construfast-ae515',
    storageBucket: 'construfast-ae515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdClHZpWINrCfbLH9GCC9L770nRASs40E',
    appId: '1:241289146857:ios:87d1813e4afdff602f9b78',
    messagingSenderId: '241289146857',
    projectId: 'construfast-ae515',
    storageBucket: 'construfast-ae515.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdClHZpWINrCfbLH9GCC9L770nRASs40E',
    appId: '1:241289146857:ios:87d1813e4afdff602f9b78',
    messagingSenderId: '241289146857',
    projectId: 'construfast-ae515',
    storageBucket: 'construfast-ae515.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhpAkcM8tqMw5jNbzNIwYZYJh0yI7akZ0',
    appId: '1:241289146857:web:736896e5bfc7c0782f9b78',
    messagingSenderId: '241289146857',
    projectId: 'construfast-ae515',
    authDomain: 'construfast-ae515.firebaseapp.com',
    storageBucket: 'construfast-ae515.firebasestorage.app',
    measurementId: 'G-HL509EJPVC',
  );

}